### ISSUE TITLE
Issue upgrading to 3.2.0 from 3.1.9

### ISSUE THREAD

**Issue by u01jmg3** [DataTables/FixedHeader#107]
Since upgrading from `3.1.9` to `3.2.0` we are seeing an issue whereby the fixed header becomes stuck at the bottom of the DataTable when you scroll.

I see there is now a new `floatingParent` introduced in `3.2.0` - is this something we can opt out of using if it has issues?

For now we will have to stick to using `3.1.9`.

<img width="630" alt="header" src="https://user-images.githubusercontent.com/1266205/137533845-92a8e8f2-73ed-4104-807c-9c701e3da94b.png">

**Comment by AllanJard** [comment]
Can you link to a test case so we can debug it please?

**Comment by AllanJard** [comment]
There were quite a lot of changes between the two, so I'm not sure how easy it will be to isolate it to a specific commit I'm afraid. There were also development bugs that were fixed in the process, so I suspect a test case with 3.2.0 is going to be the best way forward.

I don't see this issue [with any of our examples](https://datatables.net/extensions/fixedheader/examples/) so are you doing something with your table that our examples are not? Is it in a modal, or something else? It might be easier to build a new test case from the bottom up, rather than trying to strip back what you've got.

**Comment by u01jmg3** [comment]
Figured out the issue.

In `v3.1.9` we were able to use:

```js
fixedHeader: {
    header: true,
    headerOffset: $('.navbar-fixed-top').outerHeight().toFixed(1),
},
```

But now in `v3.2.0` we must use:

```js
fixedHeader: {
    header: true,
    headerOffset: parseFloat($('.navbar-fixed-top').outerHeight().toFixed(1)),
},
```

**Comment by AllanJard** [comment]
Interesting - what did `$('.navbar-fixed-top').outerHeight().toFixed(1)` resolve to in this case?

**Comment by AllanJard** [comment]
Got it - thank you! Yes, we use `headerOffset` as part of a few numeric calculations, so it would have to be a number rather than a string. Our docs have it required as [an integer](https://datatables.net/reference/option/fixedHeader.headerOffset), although any Javascript `number` would be fine.

I think since the docs do state that it should be an integer / number rather than a string, then this probably isn't something we would fix with a cast inside FixedHeader. That's the approach we've taken with other similar "overloads" for functions, since we'd just end up with loads of type checks in the code which would be 99% redundant.

**Comment by u01jmg3** [comment]
Thanks for confirming and I understand your reasoning.

I guess what threw us was that it used to accept a string but since `v3.2.0` stopped doing so. Happy to adjust our code regardless.
